language: bash

sudo: required

services:
  - docker

env:
  global:
    - LATEST_ALPINE_VER=3.6
    - DOCKER_VERSION=17.06.2
  matrix:
    - TAG=3.6 ALPINE_VER=3.6
    - TAG=3.4 ALPINE_VER=3.4

before_install:
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce="${DOCKER_VERSION}~ce-0~ubuntu"

script:
  - travis_retry make && make test

after_success: |
  if [[ "${TRAVIS_PULL_REQUEST}" == "false" && ("${TRAVIS_BRANCH}" == "master"  || -n "${TRAVIS_TAG}") ]]; then
    docker login -u "${DOCKER_USERNAME}" -p "${DOCKER_PASSWORD}"
    make release

    if [[ -n "${TRAVIS_TAG}" ]]; then
      make release TAG="${TAG}-${TRAVIS_TAG}"
    elif [[ "${ALPINE_VER}" == "${LATEST_ALPINE_VER}" ]]; then
      make release TAG="latest"
    fi
  fi
